 
create table if not exists bookmarks (
      id INTEGER primary key generated by default as identity,
      title text,
      website url,
      rating INTEGER,
);
insert into bookmarks (title,website,rating)
values 
('one', 'https://google.com',3),
('two', 'https://yahoo.com',3),
('three', 'https://google3.com',3),
('four', 'https://google4.com',3),
('five''https://google6.com',3),
('six','http,s://google7.com',3),
('seven','hhttps://googl8e.com',3),
('eight', 'https://google9.com',3),
('nine', 'https://google0.com',3),
('ten', 'https://google5.com',3);
 
psql -U dunder_mifflin -d /Users/nikadarab/dev/thinkful/week9/bookmark-server/bookmarks.sql